export default {
  CHECK_PROFILE_STATUS_START: 'CHECK_PROFILE_STATUS_START',
  CHECK_PROFILE_STATUS_SUCCESS: 'CHECK_PROFILE_STATUS_SUCCESS',
  CHECK_PROFILE_STATUS_FAILURE: 'CHECK_PROFILE_STATUS_FAILURE'
}